import yaml from 'js-yaml';import{validateDefinition,makeRecord,csvEscape}from'./runtime.js';
const KEY='openform/v1';const state=JSON.parse(localStorage.getItem(KEY)||'{"apps":{},"records":{}}');let current=null,editing=null;const $=s=>document.querySelector(s);const root=$('#app');const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const mattress={spec:'openform/definition/v1',app:{id:'mattress_quote',name:'床墊試躺 / 詢價紀錄',version:1},fields:[['store','店家','text'],['brand','品牌','text'],['model','型號','text'],['size','尺寸','text'],['price','報價','number'],['all_in_price','總價','number'],['materials','材質','textarea'],['spring','彈簧','text'],['zones','分區','text'],['edge_support','邊緣支撐','rating'],['firmness','軟硬度','rating'],['back_support','仰睡支撐','rating'],['side_comfort','側睡舒適','rating'],['motion_isolation','抗干擾','rating'],['breathability','透氣','rating'],['overall_comfort','整體舒適','rating'],['trial','試睡','text'],['returns','退換貨','text'],['warranty','保固','text'],['indentation','凹陷保固條件','text'],['delivery','配送','text'],['notes','備註','textarea']].map(([id,label,type])=>({id,label,type,...(type==='rating'?{min:1,max:id==='firmness'?10:5}:{})}))};
if(!state.apps[mattress.app.id]){state.apps[mattress.app.id]=mattress;state.records[mattress.app.id]=[];save();}
function home(){current=null;root.innerHTML=`<section class="hero"><h1>我的 App</h1><p>由 Definition 產生資料收集 App。資料目前只存在這台裝置。</p><div class="actions"><button id="mattress">使用床墊範本</button><button id="paste">匯入 Spec</button></div></section><section><h2>Apps</h2><div class="cards">${Object.values(state.apps).map(a=>`<button class="card appcard" data-id="${a.app.id}"><b>${a.app.name}</b><span>${(state.records[a.app.id]||[]).length} 筆紀錄</span></button>`).join('')}</div></section>`;$('#mattress').onclick=()=>openApp('mattress_quote');$('#paste').onclick=importSpec;document.querySelectorAll('.appcard').forEach(x=>x.onclick=()=>openApp(x.dataset.id));}
function openApp(id){current=id;const d=state.apps[id],rs=state.records[id]||[];root.innerHTML=`<section><h1>${d.app.name}</h1><div class="actions"><button id="new">新增紀錄</button><button id="json">匯出 JSON</button><button id="csv">匯出 CSV</button></div></section><section><h2>紀錄</h2>${rs.length?`<div class="cards">${rs.map((r,i)=>`<div class="card"><b>${r.data.brand||r.data.store||r.id}</b><span>${new Date(r.updated_at).toLocaleString()}</span><div class="actions"><button data-edit="${i}">編輯</button><button class="danger" data-del="${i}">刪除</button></div></div>`).join('')}</div>`:'<p>尚無紀錄。</p>'}</section>`;$('#new').onclick=()=>form();$('#json').onclick=()=>download(`${id}.json`,JSON.stringify(rs,null,2),'application/json');$('#csv').onclick=()=>exportCsv(d,rs);document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>form(+x.dataset.edit));document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{if(confirm('確定刪除？')){rs.splice(+x.dataset.del,1);save();openApp(id)}});}
function fieldHtml(f,v=''){const id=`f_${f.id}`;if(f.type==='textarea')return `<label>${f.label}<textarea id="${id}">${v??''}</textarea></label>`;if(f.type==='boolean')return `<label><input id="${id}" type="checkbox" ${v?'checked':''}> ${f.label}</label>`;if(f.type==='select')return `<label>${f.label}<select id="${id}">${(f.options||[]).map(o=>`<option value="${o.value}" ${v==o.value?'selected':''}>${o.label}</option>`).join('')}</select></label>`;if(f.type==='multi_select')return `<label>${f.label}<select id="${id}" multiple>${(f.options||[]).map(o=>`<option value="${o.value}" ${Array.isArray(v)&&v.includes(o.value)?'selected':''}>${o.label}</option>`).join('')}</select></label>`;if(f.type==='collection')return `<label>${f.label}<textarea id="${id}" placeholder="JSON array">${v?JSON.stringify(v):''}</textarea></label>`;const t={number:'number',rating:'number',date:'date',time:'time',datetime:'datetime-local',duration:'number'}[f.type]||'text';return `<label>${f.label}<input id="${id}" type="${t}" value="${v??''}" ${f.min!=null?`min="${f.min}"`:''} ${f.max!=null?`max="${f.max}"`:''}></label>`;}
function form(i=null){editing=i;const d=state.apps[current],old=i===null?null:state.records[current][i];root.innerHTML=`<section><h1>${i===null?'新增':'編輯'}紀錄</h1><form id="recordForm" class="form">${d.fields.map(f=>fieldHtml(f,old?.data?.[f.id])).join('')}<div class="actions"><button type="submit">儲存</button><button type="button" id="cancel" class="ghost">取消</button></div></form></section>`;$('#cancel').onclick=()=>openApp(current);$('#recordForm').onsubmit=e=>{e.preventDefault();const data={};for(const f of d.fields){const el=$(`#f_${f.id}`);if(f.type==='boolean')data[f.id]=el.checked;else if(f.type==='multi_select')data[f.id]=[...el.selectedOptions].map(o=>o.value);else if(f.type==='number'||f.type==='rating'||f.type==='duration')data[f.id]=el.value===''?null:Number(el.value);else if(f.type==='collection'){try{data[f.id]=el.value?JSON.parse(el.value):[]}catch{return alert(`${f.label} 必須是 JSON array`)}}else data[f.id]=el.value;}if(old){old.data=data;old.updated_at=new Date().toISOString();}else state.records[current].unshift(makeRecord(d,data));save();openApp(current);};}
function importSpec(){const raw=prompt('貼上 OpenForm Definition（YAML 或 JSON）');if(!raw)return;try{const d=yaml.load(raw),errs=validateDefinition(d);if(errs.length)return alert('驗證失敗：\n'+errs.join('\n'));if(!confirm(`建立 App：${d.app.name}？`))return;state.apps[d.app.id]=d;state.records[d.app.id]??=[];save();openApp(d.app.id);}catch(e){alert('無法解析：'+e.message)}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}function exportCsv(d,rs){const ids=d.fields.map(f=>f.id);const rows=[ids.map(csvEscape).join(','),...rs.map(r=>ids.map(id=>csvEscape(r.data[id])).join(','))];download(`${d.app.id}.csv`,rows.join('\n'),'text/csv;charset=utf-8')}
$('#homeBtn').onclick=home;home();
